<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <PackageId>ImpunityStandaloneServer</PackageId>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Authors>Jeremy Friesen</Authors>
    <Product>ImpunityNetworking</Product>
    <Description>Impunity Networking - Unity library enabling networked save state and multiplayer</Description>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Title>ImpunityNetworking</Title>
    <PackageTags>unity network tcp udp save multiplayer</PackageTags>
    <RepositoryUrl>https://github.com/rejemy/Impunity</RepositoryUrl>

    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UltraLiteDB">
      <HintPath>../ImpunityUnity/Assets/Plugins/UltraLiteDB.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../ImpunityUnity/Assets/Scripts/Impunity/Server/**/*.cs" />
    <Compile Include="../ImpunityUnity/Assets/Scripts/Impunity/ImpunityLifecycle.cs" />
  </ItemGroup>

</Project>
