<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ImpunityNetworking</PackageId>
    <Version>1.3.0</Version>
    <AssemblyVersion>1.3.0</AssemblyVersion>
    <Authors>Jeremy Friesen</Authors>
    <Product>ImpunityNetworking</Product>
    <Description>Impunity Networking - Unity library enabling networked save state and multiplayer</Description>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Title>ImpunityNetworking</Title>
    <PackageTags>unity network tcp udp save multiplayer</PackageTags>
    <RepositoryUrl>https://github.com/rejemy/Impunity</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RootNamespace>Impunity</RootNamespace>
    <AssemblyName>ImpunityUnityRuntime</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin/$(Configuration)/$(TargetFramework)/$(AssemblyName).xml</DocumentationFile>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>1591</NoWarn>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

<ItemGroup>
  <Reference Include="UnityEngine">
    <HintPath>lib/UnityEngine.dll</HintPath>
  </Reference>
  <Reference Include="UltraLiteDB">
    <HintPath>../ImpunityUnity/Assets/Plugins/UltraLiteDB.dll</HintPath>
  </Reference>
</ItemGroup>


<ItemGroup>
   <Compile Include="../ImpunityUnity/Assets/Scripts/Impunity/**/*.cs" />
</ItemGroup>

</Project>
