<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <PackageId>ImpunityCodeGenerator</PackageId>
    <Version>0.7</Version>
    <AssemblyVersion>0.7</AssemblyVersion>
    <FileVersion>0.7</FileVersion>
    <VersionPrefix>0.7</VersionPrefix>
    <Authors>Jeremy Friesen</Authors>
    <Product>ImpunityNetworking</Product>
    <Description>Impunity Networking Code Generator</Description>
    <NeutralLanguage>en-US</NeutralLanguage>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
  </ItemGroup>

</Project>
